### ISSUE TITLE
作品アイディア

### ISSUE THREAD

**Issue by osho210** [Team2-developers/Vue.js-dev#2]
今回の作品のアイディアを考えましょう
お題：ユーザ同士がコミュニケーションできるWebサービス
1人10案お願いします。

アイデアは独自性のあるものより、既存のサービスを参考に作成して方がいいかもしれません。

「山津」
・簡単なチャットアプリ(入力された情報をアルゴリズムでおじさん構文に変換)←変換のアルゴリズム
・地図を入力したデートプランを作成、データプランをユーザーの投稿として投稿、それに対するコメント機能を実装
・授業の理解度を画面に表示して、理解度の高い人と低い人とのマッチング(チャット機能)
・指定のルート登録して水たまりを発見してアラート
・カフェアプリ(お店の情報と)のマッチング(マッチングしたタイミングでチャット機能)
・応援ソングを作成し、それを評価するチャット機能
・チャットの入力情報を元に天気を表示するアプリ
・服装を評価してランキング形式で表示するアプリ
・授業内容の評価
・コードレビュー用サイト

「松崎」
・ネットコウブンのみで会話するTwitter系(Miskey)
・料理系sns(クックパット)
・ファッション系のsns(wear)
・学習系の知恵袋(Yahoo)
・ツイッター再現
・5ch再現
・インスタ再現
・画像だけで会話するTwitter系(イメージはバズってる投稿に画像で反応してる感じ)
・就活sns(esや面接で語った内容を細かく区切ってここがいいね👍やここ改善😅みたいな感じ)
・マッチング系
・天気SNS(アプリ-ウェザーニュースの空の写真機能)
・サブカル専用5ch系(感想や考察、リアルタイム実況)
・スポーツ専用5ch系(感想、リアルタイム実況)

「宮川」
・本音と建前のチャットアプリ
・方言チャット
・誰かの人生ゲーム
・AIが返信してくれる日記
・ニコニコ動物園
・自然豊かになっていく（荒れていく）ツール
・じゃんけん（心理戦）ゲーム
・全員同じものを選ぶまで終わらないゲーム
・文字化けチャット
・Forestのチームバージョン

「ゆた」
・ガジェット、デスク回りレビューサイト
・エンジニア向けのSNS
・組織内向けのイベント告知、交流サイト
・イラスト、交流周り
・タスク管理アプリ
・UdemyのWebテキスト版
・写真、風景　投稿アプリ
・ミーティング用のツール
・ゲーム募集の掲示板、交流サイト
・なんじゃもんじゃゲーム

「うまちゃん」
・簡易的な固定分を使った会話
・特定の質問箱（ジャンルを固定にする）
・前回のショッピングサイトにレビューを書く（レビューに対する、回答、謝罪etc）
・シンプルな（LINE）みたいなチャットアプリ
・シンプルな（ツイッター）みたいな掲示板系
・上げた写真に一言、写真見るだけでもいいし、感想を書いたりできる
・就活、第三者面接官（本物の面接官ではないが第三者からの質問に回答する感じで
ある程度の体制がつけるようにする)
・固定分を使った健康観察（定型文を使って簡単に体調のやり取りをできるようにする）
・質問にたいする回答型じゃなくて、ヒント型の（掲示板、勉強するよう）

**Comment by YuSa0-6** [comment]
Finish
